### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by alexeyr** [scalan/scalanizer-demo#1] opened 2015-06-14 17:29 UTC
Branch https://github.com/scalan/scalanizer-demo/tree/patch-1 together with https://github.com/scalan/scalanizer/tree/update-dependencies compiles, but `sbt test` fails:

```
[info] Compiling 16 Scala sources to F:\MyProgramming\scalanizer-demo\target\scala-2.11\classes...
[info] Ignoring duplicate plugin scalan (scalan.plugin.ScalanPlugin)
    WARNING: cannot generate converter from Col to PairCol: missing fields List(as, bs)
[info] Compiling 1 Scala source to F:\MyProgramming\scalanizer-demo\target\scala-2.11\test-classes...
[info] Ignoring duplicate plugin scalan (scalan.plugin.ScalanPlugin)
Generating random matrix 10000x10000 dense format "Array[Array[Double]]" ...
Generating random vector 10000 elements "Array[Double]" ...
Heating up JVM ...
[info] LinearAlgebraTests:
[info] - ddmvm *** FAILED ***
[info]   scala.reflect.internal.FatalError: class StringContext does not have a member f
[info]   at scala.reflect.internal.Definitions$DefinitionsClass.scala$reflect$internal$Definitions$DefinitionsClass$$fatalMissingSymbol(Definitions.scala:1190)
[info]   at scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1207)
[info]   at scala.reflect.internal.Definitions$DefinitionsClass.getMemberMethod(Definitions.scala:1242)
[info]   at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.StringContext_f$lzycompute(Definitions.scala:1428)
[info]   at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.StringContext_f(Definitions.scala:1428)
[info]   at scala.tools.reflect.FastTrack$$anonfun$1.apply(FastTrack.scala:54)
[info]   at scala.tools.reflect.FastTrack$$anonfun$1.apply(FastTrack.scala:46)
[info]   at scala.reflect.internal.SymbolTable$perRunCaches$$anonfun$newGeneric$1.apply(SymbolTable.scala:380)
[info]   at scala.tools.reflect.FastTrack.contains(FastTrack.scala:21)
[info]   at scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1191)
[info]   ...
```

Both are built against current Scalan `master` branch.

**Comment by MaxGekk** [comment] 2015-06-17 11:42
The issue is fixed by switching on scala virtualized 2.11.2

**Closed as completed by MaxGekk** 2015-06-17 11:42 UTC
